---
title: "C++ Examples"
author: "Nicholas Hathaway"
---

```{r, child="_cppEngineSetup.Rmd"}
```

```{r engineSetup, echo =FALSE}
#need to figure out a way to set engine.opts globaly, this currently doesn't work
opts_chunk$set(engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\"")
```

#Looping with cppitertools

##range

###Looping to a stop

```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools
int main(int argc, char* argv[]){
    for(auto pos : iter::range(10)){
    	std::cout << pos << "\n";
    }
    return 0;
}
```

###Looping from a start to a stop
```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools

int main(int argc, char* argv[]){
    for(auto pos : iter::range(3,10)){
    	std::cout << pos << "\n";
    }
    return 0;
}
```

###Looping from a start to a stop with step
```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools

int main(int argc, char* argv[]){
    for(auto pos : iter::range(0,10, 2)){
    	std::cout << pos << "\n";
    }
    return 0;
}
```

###Looping, going down
```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools

int main(int argc, char* argv[]){
    for (auto i : iter::range(2, -3, -1)) {
      std::cout << i << std::endl;
    }
    return 0;
}
```

###Looping, using fractional step
```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools

int main(int argc, char* argv[]){
    for(auto i : iter::range(5.0, 10.0, 0.5)) {
      std::cout << i << std::endl;
    }
    return 0;
}
```


###Looping examples that will end up producing no iterations

```{r, engine="C++", engine.opts="CXX=clang++ CXXFLAGS=\"-I../cppSetupTools/external/local/cppitertools/v0.1/cppitertools/\""}
#include <iostream>
#include <range.hpp> //from https://github.com/ryanhaining/cppitertools

int main(int argc, char* argv[]){
  //iterating to the same stop as your start will produce nothing
  std::cout << "Start loop example 1" << std::endl;
  for(auto i : iter::range(1,1)) {
    std::cout << i << std::endl;
  }
  std::cout << "End Loop example 1" << std::endl;
  
  //iterating to the a stop less than your start but wihtout a negative step will produuce nothing
  std::cout << "Start loop example 2" << std::endl;
  for(auto i : iter::range(1,0)) {
    std::cout << i << std::endl;
  }
  std::cout << "End Loop example 2" << std::endl;
  
  return 0;
}
```





